/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/RET8JjMCF1F
 */
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

export function SongInput() {
  return (
    <main className="p-4 space-y-4 bg-[#017374] text-white">
      <div className="w-full max-w-md mx-auto">
        <Card className="space-y-4 bg-[#2AA897]">
          <CardHeader>
            <CardTitle>Sound Surfer</CardTitle>
            <CardDescription className="text-gray-200">Enter a song and get a recommended playlist.</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="flex flex-col space-y-2">
              <label className="text-sm font-medium" htmlFor="song-input">
                Song Name
              </label>
              <input
                className="p-2 border border-gray-600 rounded-md bg-[#70C1B3] text-white"
                id="song-input"
                placeholder="Enter a song name"
                type="text"
              />
              <Button className="w-full bg-white text-black border-none" variant="outline">
                Get Recommendations
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
      <div className="w-full max-w-lg mx-auto">
        <Card className="space-y-4 bg-[#2AA897]">
          <CardHeader>
            <CardTitle>Recommended Playlist</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid gap-4" />
          </CardContent>
        </Card>
      </div>
    </main>
  )
}
